In [1]:
import numpy as np

<h2>Pseudorandom Number Generation</h2>

<h3><code>np.random()</code></h3>
<p>The numpy.random module supplements the built-in Python random module with
functions for efficiently generating whole arrays of sample values from many kinds of
probability distributions.These random numbers are not truly random (rather, pseudorandom) but instead
are generated by a configurable random number generator that determines deterministically
what values are created.</p>

In [2]:
# Generate samples from the standard normal distribution
samples = np.random.standard_normal(size=(4, 4))
print('Generated samples using numpy\'s random.standard_normal :\n', samples)

Generated samples using numpy's random.standard_normal :
 [[-0.72582224  0.95426141 -0.26052162 -2.88954028]
 [ 0.51482283  1.22092854  0.84764974 -0.36451381]
 [ 0.52898991 -1.16659125  0.98671605 -0.13704597]
 [-0.84883068 -0.31623944 -0.30088026 -0.63921501]]


| Function         | Description                                                   |
|------------------|---------------------------------------------------------------|
| `permutation`    | Return a random permutation of a sequence, or a permuted range |
| `shuffle`        | Randomly permute a sequence *in place*                        |
| `uniform`        | Draw samples from a uniform distribution                      |
| `integers`       | Draw random integers from a given low-to-high range           |
| `standard_normal`| Draw samples from a normal distribution (mean=0, std=1)       |
| `binomial`       | Draw samples from a binomial distribution                     |
| `normal`         | Draw samples from a normal (Gaussian) distribution            |
| `beta`           | Draw samples from a beta distribution                         |4

