In [2]:
import numpy as np

<h2>Universal Functions: Fast Element-Wise Array
Functions</h2>

<h3>Universal Function</h3>
<p>A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results</p>

In [8]:
# Create array 
arr = np.arange(10)
print('Original arr :\n', arr)
print()

# sqrt of array
print('Elementwise square root using sqrt methond :\n', np.sqrt(arr))
print()

# exponent of array
print('Elementwise exponents using exp methond :\n', np.exp(arr))
print()

Original arr :
 [0 1 2 3 4 5 6 7 8 9]

Elementwise square root using sqrt methond :
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

Elementwise exponents using exp methond :
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]



<p>Others, such as numpy.add or numpy.maximum,
take two arrays (thus, binary ufuncs) and return a single array as the result</p>

In [11]:
# Example of binary unfunc
x = np.random.default_rng(42).standard_normal(8)
y = np.random.default_rng(42).standard_normal(8)
print('x :\n', x)
print()
print('y :\n', y)
print()
print('Maximum of x and y elementwise using maximum method :\n', np.maximum(x, y))

x :
 [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259]

y :
 [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259]

Maximum of x and y elementwise using maximum method :
 [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259]


<p>In the above example, numpy.maximum computed the element-wise maximum of the elements
in x and y.</p>

<p>While not common, a ufunc can return multiple arrays. numpy.modf is one example</p>

In [17]:
# Ufuncs accept an optional out argument that allows them to assign their results into an existing array rather than create a new one
arr = np.arange(5)
print('Original arr :\n', arr)
print()
np.add(arr, 5, out=arr)
print('arr after addition using out argument :\n', arr)


Original arr :
 [0 1 2 3 4]

arr after addition using out argument :
 [5 6 7 8 9]


<h3>Some unary universal function</h3>


| Function(s) | Description |
|-------------|-------------|
| `abs`, `fabs` | Compute the absolute value element-wise for integer, floating-point, or complex values |
| `sqrt` | Compute the square root of each element (equivalent to `arr ** 0.5`) |
| `square` | Compute the square of each element (equivalent to `arr ** 2`) |
| `exp` | Compute the exponent `e^x` of each element |
| `log`, `log10`, `log2`, `log1p` | Natural logarithm (base *e*), log base 10, log base 2, and `log(1 + x)`, respectively |
| `sign` | Compute the sign of each element: `1` (positive), `0` (zero), or `–1` (negative) |
| `ceil` | Compute the ceiling of each element (smallest integer ≥ x) |
| `floor` | Compute the floor of each element (largest integer ≤ x) |
| `rint` | Round elements to the nearest integer, preserving the dtype |
| `modf` | Return fractional and integral parts of array as separate arrays |
| `isnan` | Return Boolean array indicating whether each value is NaN (Not a Number) |
| `isfinite`, `isinf` | Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions |
| `logical_not` | Compute truth value of `not x` element-wise (equivalent to `~arr`) |


<h3>Some binary universal function</h3>
### NumPy Arithmetic and Logical Functions

| Function(s) | Description |
|-------------|-------------|
| `add` | Add corresponding elements in arrays |
| `subtract` | Subtract elements in second array from first array |
| `multiply` | Multiply array elements |
| `divide`, `floor_divide` | Divide or floor divide (truncating the remainder) |
| `power` | Raise elements in first array to powers indicated in second array |
| `maximum`, `fmax` | Element-wise maximum; `fmax` ignores NaN |
| `minimum`, `fmin` | Element-wise minimum; `fmin` ignores NaN |
| `mod` | Element-wise modulus (remainder of division) |
| `copysign` | Copy sign of values in second argument to values in first argument |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparison, yielding Boolean array (equivalent to infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`) |
| `logical_and` | Compute element-wise truth value of AND (`&`) logical operation |
| `logical_or` | Compute element-wise truth value of OR (`|`) logical operation |
| `logical_xor` | Compute element-wise truth value of XOR (`^`) logical operation |
