<h2>Linear Algebra</h2>

<p>Linear algebra operations, like matrix multiplication, decompositions, determinants,
and other square matrix math, are an important part of many array libraries. Multiplying
two two-dimensional arrays with * is an element-wise product, while matrix multiplications require using a function.</p>

<p>The function dot, both an array
method and a function in the numpy namespace, is used for matrix multiplication.</p>

In [11]:
import numpy as np
from numpy.linalg import inv, qr

In [7]:
# Creata an array
x = np.array([[1, 2, 3], [4, 5, 6]])
print('Array:\n', x)

# Create another array
y = np.array([[6, 23], [-1, 7], [8, 9]])
print('\nArray:\n', y)

# Perform dot product
print('\nDot product using x.dot(y):\n', x.dot(y))

# x.dot(y) is equivalent to np.dot(x, y)
print('\nDot product using np.dot(x, y):\n', np.dot(x, y))


Array:
 [[1 2 3]
 [4 5 6]]

Array:
 [[ 6 23]
 [-1  7]
 [ 8  9]]

Dot product using x.dot(y):
 [[ 28  64]
 [ 67 181]]

Dot product using np.dot(x, y):
 [[ 28  64]
 [ 67 181]]


<p>A matrix product between a two-dimensional array and a suitably sized onedimensional
array results in a one-dimensional array.</p>

In [10]:
# Dot product with a 1-D array
v = np.array([1, 0, 1])
print('\n1-D Array:\n', v)
print('\nDot product of x and v using x.dot(v):\n', x.dot(v))

# dot product can also be performed using @ operator
print('\nDot product of x and v using x @ v:\n', x @ v)


1-D Array:
 [1 0 1]

Dot product of x and v using x.dot(v):
 [ 4 10]

Dot product of x and v using x @ v:
 [ 4 10]


<p>numpy.linalg has a standard set of matrix decompositions and things like inverse
and determinant.</p>

In [18]:
# Create an array of normally distributed random numbers of shape 5x5
rng = np.random.default_rng(12345)
X = rng.standard_normal((5, 5))
print('\nRandom Array:\n', X)

# Multiply the array by its transpose
mat = X.T @ X
print('\nMatrix product of X.T and X:\n', mat)

# Inverse the matrix
inv_mat = inv(mat)
print('\nInverse of the matrix:\n', inv_mat)

# Get identity matrix
identity = mat @ inv_mat
print('\nProduct of matrix and its inverse (Identity Matrix):\n', np.round(identity))


Random Array:
 [[-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331]
 [-0.74088465 -1.3677927   0.6488928   0.36105811 -1.95286306]
 [ 2.34740965  0.96849691 -0.75938718  0.90219827 -0.46695317]
 [-0.06068952  0.78884434 -1.25666813  0.57585751  1.39897899]
 [ 1.32229806 -0.29969852  0.90291934 -1.62158273 -0.15818926]]

Matrix product of X.T and X:
 [[ 9.83867527  1.04334204  0.24651754  0.04017965  0.16391486]
 [ 1.04334204  5.11794735 -3.98521413  0.99264687  3.27464142]
 [ 0.24651754 -3.98521413  4.15026075 -2.41299778 -2.74788646]
 [ 0.04017965  0.99264687 -2.41299778  3.97263789 -0.04472489]
 [ 0.16391486  3.27464142 -2.74788646 -0.04472489  6.01956209]]

Inverse of the matrix:
 [[ 0.15548538 -0.36723081 -0.52638547 -0.2300642  -0.04646089]
 [-0.36723081  2.54917814  3.47827334  1.48196722  0.22206454]
 [-0.52638547  3.47827334  5.46389554  2.46214396  0.63467543]
 [-0.2300642   1.48196722  2.46214396  1.38302896  0.33430132]
 [-0.04646089  0.22206454  0.63467543  0.334

### NumPy Linear Algebra Functions

| Function | Description |
|----------|-------------|
| `np.diag` | Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal |
| `np.dot` | Matrix multiplication |
| `np.trace` | Compute the sum of the diagonal elements |
| `np.linalg.det` | Compute the matrix determinant |
| `np.linalg.eig` | Compute the eigenvalues and eigenvectors of a square matrix |
| `np.linalg.inv` | Compute the inverse of a square matrix |
| `np.linalg.pinv` | Compute the Moore-Penrose pseudoinverse of a matrix |
| `np.linalg.qr` | Compute the QR decomposition |
| `np.linalg.svd` | Compute the singular value decomposition (SVD) |
| `np.linalg.solve` | Solve the linear system `Ax = b` for `x`, where `A` is a square matrix |
| `np.linalg.lstsq` | Compute the least-squares solution to `Ax = b` |
